<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <RootNamespace>CSM_Database_Core</RootNamespace>
	    <PackageId>CSM.Database.Core</PackageId>
		<Version>7.0.0</Version>
		<Authors>Renato Urrea</Authors>
		<Company>Cosmos (CSM)</Company>
		<RepositoryUrl>https://github.com/Cosmos-CSM/csm_database</RepositoryUrl>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageReadmeFile>CHANGELOG.md</PackageReadmeFile>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="CHANGELOG.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CSM.Foundation.Core" Version="4.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
	</ItemGroup>

</Project>
