name: Version Update Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.head_ref == 'dev'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Define project path
        id: config
        run: |
          echo 'project_path="CSM Foundation Database/CSM Foundation Database.csproj"' >> $GITHUB_OUTPUT

      - name: Get version from PR branch
        id: pr_version
        run: |
          PROJECT_PATH=${{ steps.config.outputs.project_path }}
          VERSION_PR=$(grep -oPm1 "(?<=<Version>)[^<]+" "$PROJECT_PATH")
          echo "version_pr=$VERSION_PR" >> $GITHUB_OUTPUT

      - name: Get version from main branch
        id: main_version
        run: |
          PROJECT_PATH=${{ steps.config.outputs.project_path }}
          git fetch origin main
          VERSION_MAIN=$(git show origin/main:"$PROJECT_PATH" | grep -oPm1 "(?<=<Version>)[^<]+")
          echo "version_main=$VERSION_MAIN" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          echo "PR version: ${{ steps.pr_version.outputs.version_pr }}"
          echo "Main version: ${{ steps.main_version.outputs.version_main }}"
          if [ "${{ steps.pr_version.outputs.version_pr }}" == "${{ steps.main_version.outputs.version_main }}" ]; then
            echo "❌ Version has not been updated!"
            exit 1
          else
            echo "✅ Version updated."
          fi
